### ISSUE TITLE
Add context (right click) menus

### ISSUE THREAD

**Issue by cmyr** [xi-editor/druid#101]
These should be using native menus wherever possible.

**Comment by cmyr** [comment]
Okay, here's an actual sketch for this; threading the needle between mac and windows is a bit subtle.

### Windows

In win32, context menus are intended to be displayed during handling of the [`WM_CONTEXTMENU`] message. This message is called *after* `WM_RBUTTONUP`; that is, if the application has not handled the right mouse button, then it is called again with a message telling it to display a context menu.

### macOS

In Cocoa, the default implementation of [`rightMouseDown:`] calls [`menuForEvent:`], and presents a menu if it is returned. If it is not returned, the mouse event continues up the responder chain.

## A preliminary design

We would like some API that works well in both cases, without interfering with other event flow.

What seems easiest: on **right mouse down**, we check if the running application would like to display a context menu. We add two new methods to `druid-shell::WinHandler`, that look something like:

```rust
fn context_menu(&mut self, pos: Point, ctx: &mut dyn WinCtx) -> Option<Menu>;
fn context_menu_end(&mut self, cmd: Option<Action>);
```

`context_menu` is called on right mouse down. If this method returns `Some`, then the right mouse up/down/moved events are suppressed while the menu is displayed. If it returns `None`, then the right mouse events are sent as normal. `context_menu_end` is called anytime the menu is closed, and includes a cmd if one was selected.

## What is a menu?

The type of `Menu` is not totally clear. There are currently `Menu` types declared in each `druid-shell` backend, and these may be reused; I'm not sure exactly the state of that code. I could also imagine `Menu` being a platform-independent 'menu description', that is then turned into some concrete platform-specific object in `druid-shell`. (This pattern echoes the changes to `Color` and `Gradient` in piet that have [been recently discussed][color changes].

The type of the `cmd` argument is up for discussion.

[`menuForEvent:`]: https://developer.apple.com/documentation/appkit/nsview/1483231-menuforevent
[`rightMouseDown:`]: https://developer.apple.com/documentation/appkit/nsview/1806802-rightmousedown
[`WM_CONTEXTMENU`]: https://docs.microsoft.com/en-us/windows/win32/menurc/wm-contextmenu
[color changes]: https://xi.zulipchat.com/#narrow/stream/147926-druid/topic/environments/near/172514759

**Comment by raphlinus** [comment]
Sounds like a good start. A few other thoughts.

First, to what extent is `WM_CONTEXTMENU` and `menuForEvent:` actually necessary for correct context menu operation, and to what extent is it the platform helpfully offering assistance for mouse events? In the latter case it's not actually helpful, because we can do dispatching in a platform-independent way.

Second, it's certainly a choice to use platform menus. I'm in favor, but I'll point out that they don't necessarily match the appearance of the rest of the app. I strongly suspect this will be smoother on macOS than Windows.

The current `Menu` types need some more work. I suspect it's possible to make them support contextual menus as well as the traditional drop-down menu bar; on Windows it's the same objects underneath.
