### ISSUE TITLE
druid-shell/gtk: Implement smooth scrolling

### ISSUE THREAD

**Issue by mrandri19** [xi-editor/druid#215]

**Comment by ForLoveOfCats** [comment]
Is this implemented on Windows or macOS?

**Comment by Finnerale** [comment]
As far as I know, we don't have this on any platform yet?
If that is the case, then I would close this in favor of the more general #73.

**Comment by mrandri19** [comment]
I don't know about the other plaforms, this I believe was created because of this comment:
https://github.com/xi-editor/druid/blob/master/druid-shell/src/platform/gtk/window.rs#L425

**Comment by ForLoveOfCats** [comment]
GTK handles scroll inputs from trackpads and the like differently from most mouse scroll wheels (though on some systems it muddies the two which is extra confusing). Instead of the normal left/right/up/down scroll input we normally get instead we get a 2d delta vector. GTK annoyingly enough calls this smooth scrolling (perhaps there is some existing precedent for this) instead of the animated scrolling that one might usually associate with the term "smooth scrolling".

I think our handling of these events is pretty solid on the shell side at this point and animated scrolling (if at all tangentially related to the original issue) will need to wait until we decide on how the scrolling duties should handled in various situation (such as widgets that need to be able to scroll themselves ect) and will be shell independent so I'm in favour of closing this issue

**Comment by Finnerale** [comment]
Thanks @mrandri19 and @ForLoveOfCats, I'll close this then.
