### ISSUE TITLE
pass scroll information through PaintCtx

### ISSUE THREAD

**Issue by cmyr** [xi-editor/druid#222]
In order to draw efficiently, a view in a scroll widget needs to know what region is currently visible. The simplest way to do this would be to pass through an `offset` with the `PaintCtx`. This could either be an `Option<Vec2>` (that is `None` if this view is not in a scroll widget) or a `Vec2` that is `(0., 0.)` when not in a scroll view.

At some point in the near future I'd also like to give the scroll widget the ability to zoom, and that state will have to be threaded through in a similar fashion.

**Comment by raphlinus** [comment]
For optimization, what should be passed is a visible region. The contract is that the `paint` method is only responsible for validating what's in the region. For simplicity, this region can be a rectangle, though a planned evolution to finer-grained incremental repaint might give you sparser damage regions. Therefore, I would suggest a new `Region` type, with `get_enclosing_rect() -> Rect` and `intersects(impl Into<Region>) -> bool`, initially implemented as a `Rect` newtype.

The region would also take care of zooming, as long as the zooming is done at the vector graphics level. However, there's a good case that's not how it should be done, as UI text becomes unreadable when zooming out, etc. Various forms of zooming are also desirable for accessibility (in this case, you do want UI text to become larger).

Similarly, the app may want to be aware of scroll location so it can do effects like parallax scroll. This is a separate issue than paint optimization, and requires changes to the event flow - interest needs to be registered so that the contents will get an `update` on scroll, something we want to avoid in the general case. It's tempting to fudge this because we're basically doing the equivalent of imgui now in terms of drawing efficiency, but I don't want to lock us in to that.

**Comment by cmyr** [comment]
`Region` sounds good. Agree that zooming is special; in the very simple case of runebender, I want zooming to change the scale of the artboard and glyph outlines, but I don't want it to change the scale of control handles or labels.

I have in my head the idea of a widget being 'scroll aware'; that is, a widget that is placed in a scroll view that wants to take advantage of zoom has to be designed for it; this is similarly true for a widget that wants to draw more efficiently when

I think that zoom for accessibility is a separate concern.

**Comment by raphlinus** [comment]
I think we're on the same page, lemme summarize. There are two different concerns, one is an optimization where widgets don't have to do anything, but have access to the visible region. The other is an explicit opt-in "scroll aware" (which might include being "zoom aware", perhaps as a separate opt-in for performance reasons), which causes `update` propagation.

Also at some point, we want paint region optimization, so a `Row` or `Column` can skip calling `paint` for widgets outside the visible region. But right now we don't know what the paint regions are - they're *usually* the layout region (which we do know), but that's nowhere enforced. It's possible we do a q&d version of that where we use the layout region, but it would also be nice to get the signature in place.

**Comment by cmyr** [comment]
Closed in #226
