### ISSUE TITLE
impl Data for basic piet and kurbo types

### ISSUE THREAD

**Issue by cmyr** [xi-editor/druid#485]
We should include these in data.rs. I would have impls for all the basic geometry types, as well as `Color`, and maybe the various gradient types?

**Comment by Malmz** [comment]
Looking at this. Is there a reason why kurbo types like Rect don't derive PartialEq?

**Comment by raphlinus** [comment]
That's been a somewhat contentious issue. There are a number of issues with `PartialEq`, including the fact that in many contexts floating point roundoff error makes exact equality tests inadvisable, and also the fact that it is never true for NaN and infinity values. I personally have been fairly conservative in derives, only adopting them when I see a convincing case the trait is useful (others are more liberal, feeling more or less that all basic traits like PartialEq and Debug should be derived when they can be).

In any case, PartialEq is not a satisfactory impl of the `Data` type, nor is PartialEq on Rect's elements, mostly because of the NaN issue.

**Comment by cmyr** [comment]
because floating point comparison is fraught, and we wanted to "get it right", because kurbo has aspirations to correctness.

**Comment by Malmz** [comment]
Some very valid reason. One option could be to implement PartialEq manually for Rect and others with f32::to_bits.

**Comment by cmyr** [comment]
that doesn't really solve the underlying problem, unfortunately. The robust solution will be to use a separate `FuzzyEq` trait, likely based on something like [float-cmp](https://docs.rs/float-cmp/0.6.0/float_cmp/), but this is a fairly significant project. In particular I think we need an API that supports both explicitly passing epsilon/ULP, but also something that has a reasonable implementation that requires no arguments and which works in the basic case, and actually figuring out what that would look like is (for me at least) a research project.

**Comment by cmyr** [comment]
What I would suggest is just implementing `Data` for each of the foundational types, using bitwise equality. It should be pretty straight forward, it will just involve a reasonable amount of typing/copy paste. `Data` does not require partialeq.

**Comment by raphlinus** [comment]
Yeah, intuition for the `Data` type is C `memcmp` (bitwise equality on the representation) on the struct. In the case of `Arc`, that's bitwise equality of the pointer.
