### ISSUE TITLE
Failure to deliver mouse events outside of the window

### ISSUE THREAD

**Issue by cmyr** [xi-editor/druid#541]
Druid expects to receive a mouse move event when the mouse moves outside of the window.

This currently is not delivered on the gtk backend. I haven't tested on windows, but I suspect it may have a similar problem.

It is not necessary that we receive _all_ events outside the window, but it is pretty important that we receive at least one. On platforms that have mouse entered/exited notifications, it would be acceptable to handle that on the platform and send `mouse_moved` to druid-shell then.

**Comment by ForLoveOfCats** [comment]
Does the Cocoa backend send all mouse events when the point is outside the window bounds? It is pretty important for all backends to do that so that you can eg continue to drag scrollbars when the mouse leaves the window, but as the Cocoa is the current "gold standard" backend it would be good to get the behavior the same on GTK (and Windows if it is not already) then upgrade them all to send all mouse events if necessary.

**Comment by cmyr** [comment]
These are slightly different issues: when a mouse button is pressed inside our window we want to capture all events, (see #457) but if the mouse is not pressed we only *need* to know if it has left the window.

**Comment by raphlinus** [comment]
I might not be understanding everything, but I think the issue here is when the mouse is pressed inside the window, then dragged away while the button is held down. I haven't validated this, but my impression is that macOS continues to deliver mouse events until button-up, while Windows does not do this by default, but does provide a [SetCapture](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setcapture) function that can provide this behavior.

**Comment by cmyr** [comment]
that is a separate issue (#457). This is for knowing when the mouse has left the window when there is no mouse button pressed.

**Comment by raphlinus** [comment]
Ah ok, disregard then.

**Comment by raphlinus** [comment]
Do we want this to simply be a mousemoved event with coordinates outside the window, or do we want to have a separate mouseleave event that specifically indicates that? I believe that on Cocoa the right way to that is a [mouseExited:](https://developer.apple.com/documentation/appkit/nsresponder/1527561-mouseexited?language=objc) event after setting up a tracking area.

**Comment by cmyr** [comment]
things are working fine on cocoa, which always delivers mouse events to the active window. The easiest course of action is to just deliver a mousemoved event with coordinates outside the window on other platforms.
