### ISSUE TITLE
WinCtx thoughts

### ISSUE THREAD

**Issue by cmyr** [xi-editor/druid#543]
# What's up with `WinCtx`

So I'm trying to understand a bit better the genesis of `WinCtx`. It's introduced in #77,
as part of a general strategy for avoiding reentrancy problems, but there are a number
of things happening in that patch and it isn't totally clear where `WinCtx` fits in.

As I understand it, the idea of `WinCtx` was to be an alternative to having `druid` hold
on to a bag of `WindowHandle`s. By passing in the `WinCtx` with each window method,
we could guarantee that it was always valid, or at least did not persist between calls.

Q: Is this the correct rationale?

Q: Are there any specific concerns related to calling methods on `WindowHandle` directly,
that are addressed by passing in `WinCtx`?

As I currently understand things, there are two issues around `WinCtx`, as it currently exists:

The biggest issue is when we want to deal with multiple windows; if we handle an event
from one window, we cannot then send an event to another window with the correct
`WinCtx`. This also means, for instance, that in `update` (which is called on all
windows after one window handles an event) we cannot get the appropriate `WinCtx` for
each window, which we would need if (for instance) we wanted to be able to start
a timer in `update`, given the current API. This will also be an issue if we want
to introduce an `AppHandler`; that type won't get a `WinCtx`, and will require
its methods to all have slightly different signatures.

The second issue is related, which is just that it is very hard to create a `WinCtx`,
which caused a bunch of headaches when I was writing the testing stuff.

Naively, the easy feeling answer to this problem is to get rid of `WinCtx`, and go
back to using handles directly when required, finding some other mechanism for
guarding against the kinds of problems that `WinCtx` was intended to address.

### Text

A more mysterious aspect of `WinCtx`, to me, is that it provides access to a `piet::Text`
object that can be used to do text layout.

This is an important feature that we need, and I'm not sure what a reasonable alternative is.

What alternatives do we have to passing this in with each event?

A simple version might just be that `WindowHandle` gets a method that can pass
out a `Text` object. This might require the `WindowHandle` API to become a bit
more defensive; we might want to require the user to lock or check a handle before
it can be used, to ensure that pointers are valid/resources exist?

### Anyway:

mainly what I'm striving towards here is a better understanding of the rationale for
adopting `WinCtx`, and a better sense of what issues I should be keeping in mind
when considering alternatives.

**Comment by raphlinus** [comment]
Your understanding is correct. The dual motivation was (a) to reduce interior mutability, and (b) to provide access to a text factory to methods other than `paint`. There's no need to provide a text factory to `paint` because it comes "for free" with the piet `RenderContext`.

Motivation (a) feels no longer valid in a multi-window world. The `WinCtx` can provide relevant access to the window currently being dispatched, but not access to other windows. There needs to be another mechanism for this, and interior mutability to a `WindowHandle` is probably the best such thing. (By "access" I mean: invalidating the window, fetching its dpi, posting messages to it).

I believe the text factory can be considered effectively global to the program; there's probably no need to keep one per-window.

I don't have the full answer here. It's possible that moving from window state towards application state can help. For example, dpi could be `HashMap<WindowId, Dpi>`, and an invalidate call could be something along the lines of `AppCtx.invalidate(WindowId)`, for which the implementation would dispatch it to the window.

**Comment by cmyr** [comment]
Do you think it makes sense to get rid of `WinCtx` entirely? Are there any clear concerns this would raise?

**Comment by raphlinus** [comment]
I'm trying to think of any concerns, but I think if all its functions (including text factory) are migrated into other mechanisms, it does make sense for it to go away.
