### ISSUE TITLE
Lists with TouchScreen

### ISSUE THREAD

**Issue by MGlolenstine** [xi-editor/druid#577]
Would it be possible, to add a way to scroll `list`s by using touch? 
We can use mouse scroll wheel and touchpad, but not touchscreen.

**Comment by cmyr** [comment]
Touch is something that is interesting eventually, but we are trying not to commit to right now; support for mobile in general is a huge increase in scope, and our current focus is 'traditional' desktop applications.

So: maybe, eventually, but this is not currently on the roadmap. If a highly motivated contributor wanted to really dig into this and write up a proposal we could consider it, but otherwise it will have to wait.

**Comment by cmyr** [comment]
The problem is that touch really has different properties from a mouse pointer; not only do you have to contend with multiple simultaneous touches, but you also the whole model of what constitutes movement or a click are different.

There was a WIP fork getting druid working on android at some point, but it was limited in some of these major ways.
