### ISSUE TITLE
Define the current scope of druid in the readme

### ISSUE THREAD

**Issue by Finnerale** [xi-editor/druid#806]
Could be nice to add a note what druid is / will be and what it's not.
Probably also refer to alternatives for the out-of-scope things such as embedding.

That's what came to my mind:

Goals:
- Pure rust
- Easy creation of custom / special purpose widgets
- Cross platform with good integration regarding application behavior
- Basic set off widgets for most use cases
- Easy packaging for different platforms

Non-Goals:
- Native style widgets
- Embedding with custom renderer / shell

What else could be added?

**Comment by mitchmindtree** [comment]
This would be very helpful!

A couple of questions that come to mind related to druid's scope:

- Is there any interest in exposing an API that allows users to implement their own rendering backend? E.g. I'm imagining something where, when it's time to render, druid provides an ordered list of commands primitives (e.g. text, paths, geometry and textures/IDs) and allows the user to render them as they desire? Or perhaps a list of higher-level "commands" might be more suitable as you could also describe the order of actions like `SetScissor`, `DrawPrimitives(Primitives)`, etc?
- is it possible for users to use druid with existing `winit` based applications? Would providing an input event abstraction that allows for doing so be considered as a goal for druid?

**Comment by xStrom** [comment]
Regarding providing a rendering backend abstraction, I think we already have that in [piet](https://github.com/linebender/piet). You can recompile druid with a custom piet backend and do your custom rendering.

Regarding using with existing applications, I think there's some work undergoing in relation to DAW to allow druid to be used from inside other applications.

As for using `winit` inputs, I guess it might be possible to write a `winit` druid-shell backend.

**Comment by cmyr** [comment]
Some goals that come to mind:

- focus on traditional desktop 'pc' applications (explicitly not mobile, right now)
- small and fast binaries
- running an application is a single `cargo build` away

And there are other 'goals', like robust localization and accessibility support that we're definitely far away from but maybe still worth acknowledging?

**Comment by xStrom** [comment]
Goals:
* Fast and memory efficient (unlike a lot of other cross-platform GUI toolkits)
* Secure and sound (This requires commitment to strong policies and thorough code reviews)

One of the policies that we would need to achieve these two would be to have a high quality barrier to adding new non-trivial default features, and external dependencies.

Adding new features will always have a complexity cost. Drive-by contributions of large scope are the riskiest here, especially if the feature doesn't have wide interest but is intertwined with core code. The new parts will either be ignored by maintainers and will cause bit rot or they will be a low value time sink because maintainers will have to throughly learn the code.

Thus I think large features should only be accepted when they're coming from a regular contributor, or have a clear common use, or some other maintainer accepts the maintenance burden. Basically it boils down to all code needing a reasonably active maintainer.

There's no easier way to get a ton of bloated and buggy code than to add a dependency that is really a whole tree of dependencies. Open source is great, but not all open source projects are created equal. If left unchecked then the dependencies we use won't have the same policies and code review practices for accepting changes. So dependency updates are a great way to get bloat and hard to track down bugs.

Dependencies also tend to do a lot more than we need for druid. This means slower compile times but also limited attention from the dependency authors. For example there's been some talk around `winit` and how it fails to achieve druid's performance goals. Instead we've done fairly well with our own more focused `druid-shell`. A large dependency also means that even if we ourselves will fix issues inside of it, the issue fixing will require more work due to the larger scope of the dependency. Just recently when working on mouse events I ran into some interesting behavior and went to check out how `winit` handles the issue, only to find out that the `winit` mouse handling code is somewhat of a mess. I was rather happy that I can work on the fix in the comparatively limited scope of `druid-shell` and I won't have to start yak shaving all the needed edge cases to fix the mouse code in `winit` instead.

Thus dependency wise I think there's an opportunity to be more nimble and efficient by solving a bunch of problems ourselves within our own scope, instead of just importing a bunch of kitchen sink libraries of variable quality.

When deciding whether to add a dependency, the dependency itself should undergo a review according to some policy that we need to set. We should prefer dependencies where we actually use a large part of it and the value of using it over solving the problem ourselves will outweigh the cost of all future maintenance that we ourselves might need to do on that larger scope dependency. This calculation also needs to account for the probability of the dependency's scope increasing even more over time.

Additionally it would be good to review the general project management practices of the dependency and how well they match our own. For some dependencies the frequency of updates and the number of significant maintainers can also play a role.

One of the steps we should probably take is automating some of this dependency growth checking. [cargo-deny](https://github.com/EmbarkStudios/cargo-deny) might be useful here. There's also a decent [talk](https://fosdem.org/2020/schedule/event/rust_cargo_deny/) about it.

**Comment by Finnerale** [comment]
So as I would like to get this done before we release 0.6, how about something like this:

**Goals**:
- Make it easy to build and package on all supported platforms.
- Provide abstractions to avoid platform specific quirks.
- Encourage good application behavior across platforms.
- Produce small and fast binaries with low memory usage.
- Have a small dependency tree with a high quality code base and good organization.
- Focus on powerful, desktop-grade applications.
- Provide the basic set of widgets needed by most applications.
- Simplify creation of complex, special purpose widgets.

**Non-Goals**
- Use the the platform-native widgets or mimic them. (relm)
- Embed easily into custom render pipelines. (Conrod)
- Implement a specific architectural style such as Elm. (Iced, relm)
- Support rendering to HTML when compiling for WASM. (Iced, Moxie)
- Support for older Rust versions.
- API stability anytime soon.

**Comment by xStrom** [comment]
That's a good summary!

I think we should mention the goal of polish pretty much at the top of the goals list, not unlike @cmyr mentioned at the start of #434. Perhaps something like:
* Provide a smooth and polished user experience with pixel perfect design and no behavioral quirks.

I would also add the following to the goals list:
* Automate platform resolution independence.
* Enable robust internationalization.
* Ensure accessibility to a wide group of people.

I also think that temporary stuff like supporting older Rust versions and API stability shouldn't be under non-goals, because they probably are goals. We're just not ready for them. Could just remove those two. Alternatively could have a third list titled *Experimental stage* or something.

**Comment by Finnerale** [comment]
I think I'll cook up a PR then :smile:
