### ISSUE TITLE
The invalidation example behaves differently with wasm

### ISSUE THREAD

**Issue by Finnerale** [xi-editor/druid#872]
When testing the wasm examples after #817 I noticed that it behaves differently to the native version.
While the left side seems to work perfectly fine, on the right only one rect is visible at a time.
This seems to indicate that the entire right half gets invalidated?
Maybe @jneem has an Idea.

**Comment by jneem** [comment]
There's some difference between how backends handle invalidation: in cairo/gtk, the `CairoRenderContext` that we get from the system is already clipped to the invalid rect. I think that in windows/mac/wasm, it isn't. That means that anything druid paints outside the invalidation rect will appear on some systems but not others. I'm not sure that this is a bug as such, because contents outside the invalidation rect shouldn't be changing anyway. (The `DebugInvalidation` widget is breaking the rules here, but I think that's unavoidable.)
