### ISSUE TITLE
Unable to filter directories on GTK file dialogs.

### ISSUE THREAD

**Issue by cmyr** [xi-editor/druid#947]
This was reported in runebender (https://github.com/linebender/runebender/issues/108); apparently the patch that added file type filtering to gtk (#903?) means we're no longer able to open directories, even with the `select_directories` option set.

**Comment by Finnerale** [comment]
Selecting directories works perfectly fine when not using `allowed_types`.

Using `allowed_types` + `select_directories` is 'broken' indeed, but I do not think we can do anything about that on our end.

The problem with the combination is that you can only navigate bookmarks, but not 'go into' any directories in the dialog because they are filtered out. But if you have a bookmark that gets you to a folder containing a `my_font.ufo` *directory* than that works perfectly fine (it is selectable).

**Comment by xStrom** [comment]
I think the GTK implementation can ignore `allowed_types` when `select_directories` is `true`. This would put it on bar with Windows, where Windows itself will ignore `allowed_types`  in that case.

There is no way (using the standard file dialog without extensions) to filter directories on Windows, so I don't think this is a behavior that druid can provide in a cross-platform way.

**Comment by cmyr** [comment]
That sounds reasonable to me.
